-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 03:10:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Course` (
  `courseNumber` VARCHAR(25) NOT NULL,
  `courseName` VARCHAR(45) NOT NULL,
  `Professor` VARCHAR(45) NOT NULL,
  `Cancelled` VARCHAR(45) NOT NULL,
  `Office_Hours` VARCHAR(45) NOT NULL,
  `Meet_Time` VARCHAR(45) NOT NULL,
  `Room` VARCHAR(45) NOT NULL,
  `Semester` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`courseNumber`, `Semester`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
